/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as ModpacksLayoutRouteImport } from './pages/modpacks/layout'
import { Route as IndexRouteImport } from './pages/index'
import { Route as ModpacksIndexRouteImport } from './pages/modpacks/index'
import { Route as ModpacksIdIndexRouteImport } from './pages/modpacks/$id/index'

const ModpacksLayoutRoute = ModpacksLayoutRouteImport.update({
  id: '/modpacks',
  path: '/modpacks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModpacksIndexRoute = ModpacksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModpacksLayoutRoute,
} as any)
const ModpacksIdIndexRoute = ModpacksIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => ModpacksLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modpacks': typeof ModpacksLayoutRouteWithChildren
  '/modpacks/': typeof ModpacksIndexRoute
  '/modpacks/$id': typeof ModpacksIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modpacks': typeof ModpacksIndexRoute
  '/modpacks/$id': typeof ModpacksIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modpacks': typeof ModpacksLayoutRouteWithChildren
  '/modpacks/': typeof ModpacksIndexRoute
  '/modpacks/$id/': typeof ModpacksIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modpacks' | '/modpacks/' | '/modpacks/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modpacks' | '/modpacks/$id'
  id: '__root__' | '/' | '/modpacks' | '/modpacks/' | '/modpacks/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModpacksLayoutRoute: typeof ModpacksLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/modpacks': {
      id: '/modpacks'
      path: '/modpacks'
      fullPath: '/modpacks'
      preLoaderRoute: typeof ModpacksLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modpacks/': {
      id: '/modpacks/'
      path: '/'
      fullPath: '/modpacks/'
      preLoaderRoute: typeof ModpacksIndexRouteImport
      parentRoute: typeof ModpacksLayoutRoute
    }
    '/modpacks/$id/': {
      id: '/modpacks/$id/'
      path: '/$id'
      fullPath: '/modpacks/$id'
      preLoaderRoute: typeof ModpacksIdIndexRouteImport
      parentRoute: typeof ModpacksLayoutRoute
    }
  }
}

interface ModpacksLayoutRouteChildren {
  ModpacksIndexRoute: typeof ModpacksIndexRoute
  ModpacksIdIndexRoute: typeof ModpacksIdIndexRoute
}

const ModpacksLayoutRouteChildren: ModpacksLayoutRouteChildren = {
  ModpacksIndexRoute: ModpacksIndexRoute,
  ModpacksIdIndexRoute: ModpacksIdIndexRoute,
}

const ModpacksLayoutRouteWithChildren = ModpacksLayoutRoute._addFileChildren(
  ModpacksLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModpacksLayoutRoute: ModpacksLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
